[package]
name = "cparser"
version = "0.1.0"
edition = "2024"

[dependencies]
clang = "2.0.0"
petgraph = "0.6.3"
dot = "0.1.4"
structopt = "0.3.26"
anyhow = "1.0.70"
regex = "1.8.1"
serde_json = "1.0"
serde = {version="1.0.219", features=[]}
